export const ROUTES = {
  dashboard: "/dashboard",
  productManagement: "/dashboard/product-management",
  sales: "/dashboard/sales",
  inventory: "/dashboard/inventory",
  updateInventory: "/dashboard/inventory/updateInventory",
  triggerOrder: "/dashboard/inventory/triggerorders",
  category: "/dashboard/categories",
  returns: "/dashboard/returns",
  viewReturns: "/dashboard/returns/view_returns",
  customer: "/dashboard/customer",
  happyTime: "/dashboard/happy-time",
  happyDiscountAnalytics: "/dashboard/happy-time/analytics",
  transaction: "/dashboard/transaction",
  stores: "/dashboard/stores",
  report: "/dashboard/reports",
  createOrder: "/dashboard/sales/create_order",
  viewOrder: "/dashboard/sales/view_order",
  test: "/dashboard/#",
  addNewProduct: "/dashboard/product-management/add-new-product",
  addBulkProduct: "/dashboard/product-management/add-bulk-product",
};
