export const ROUTES = {
  HOME: "/",
  dashboard: "/dashboard",
  productManagement: "/dashboard/product-management",
  sales: "/dashboard/sales",
  viewOrderdraft: "/dashboard/sales/draft",
  previewdownload: "/dashboard/sales/preview-download",
  inventory: "/dashboard/inventory",
  updateInventory: "/dashboard/inventory/updateInventory",
  triggerOrder: "/dashboard/inventory/triggerorders",
  category: "/dashboard/categories",
  subCategory: "/dashboard/categories/sub-categories",
  subCategoryBusinessUnit: "/dashboard/categories/sub-categories",
  categoryCollection: "/dashboard/categories/collection",
  returns: "/dashboard/returns",
  viewReturns: "/dashboard/returns/view_returns",
  customer: "/dashboard/customer",
  happyTime: "/dashboard/happy-time",
  happyDiscountAnalytics: "/dashboard/happy-time/analytics",
  happyGiftCard: "/dashboard/happy-time/gift_card",
  transaction: "/dashboard/transaction",
  stores: "/dashboard/stores",
  viewStore: "/dashboard/stores/view",
  storeTarget: "/dashboard/stores/store_target",
  storeBillingInformation: "/dashboard/stores/billing-information",
  aboutProduct: "/dashboard/stores/about_product",
  report: "/dashboard/reports",
  reportDateSelect: "/dashboard/reports/report-date-input",
  salesProcessing: "/dashboard/reports/sales-processing",
  productManagementReport: "/dashboard/reports/product-management",
  returnsRefundsReport: "/dashboard/reports/returns-refunds",
  createOrder: "/dashboard/sales/create_order",
  viewOrder: "/dashboard/sales/view_order",
  test: "/dashboard/#",
  addNewProduct: "/dashboard/product-management/add-new-product",
  addBulkProduct: "/dashboard/product-management/add-bulk-product",
  viewProduct: "/dashboard/product-management/view-product",
  editProduct: "/dashboard/product-management/edit-product",
  inventoryDetails: "/dashboard/product-management/inventory-details",
  viewTransaction: "/dashboard/transaction/view-transaction",
  viewPendingTransaction: "/dashboard/transaction/view-pending-transaction",
  previewTransaction: "/dashboard/transaction/preview-transaction",

  // PROCUREMENT SECTION

  procurementDashboard: "/dashboard/procurement",
  newRequest: "/dashboard/procurement/new-request",
  createdRequest: "/dashboard/procurement/created-request",
  viewApproveRequest: "/dashboard/procurement/view-approve-request",
  viewPendingRequest: "/dashboard/procurement/view-pending-request",
  viewCancelledRequest: "/dashboard/procurement/view-cancelled-request",
  purchaseOrder: "/dashboard/purchase-order",
  createPurchaseOrder: "/dashboard/purchase-order/create-purchase-order",
  purchaseInvoicePage: "/dashboard/purchase-order/purchase-invoice",
  viewPurchaseOrderInvoicePage:
    "/dashboard/purchase-order/view-purchase-order-invoice",
  vendorManagement: "/dashboard/vendor-management",
  tierOneVendors: "/dashboard/vendor-management/tier-one-vendor",
  tierTwoVendors: "/dashboard/vendor-management/tier-two-vendor",
  createTierOne: "/dashboard/vendor-management/create-tier-one",
  createTierTwo: "/dashboard/vendor-management/create-tier-two",
  editVendor: "/dashboard/vendor-management/edit-vendor",
  requestDashboard: "/dashboard/request-dashboard",
  requestSummaryPage: "/dashboard/request-dashboard/request-summary-page",
  viewBudgetPage: "/dashboard/request-dashboard/view-budget-page",
  shipments: "/dashboard/shipments",
  shipmentsSummary: "/dashboard/shipments/summary",
  createShipment: "/dashboard/shipments/create-shipment",
  purchaseReturns: "/dashboard/purchase-returns",
  approveReturns: "/dashboard/purchase-returns/approve-returns",
  issuePurchase: "/dashboard/purchase-returns/issue-purchase",
  goodsReceived: "/dashboard/goods-received",
  pendingNoteDetails: "/dashboard/goods-received/pending-note-details",
  rejectedNoteDetails: "/dashboard/goods-received/rejected-note-details",
  approvedNoteDetails: "/dashboard/goods-received/approved-note-details",

  // ASSET MANAGEMENT SECTION

  assetDashboard: "/dashboard/asset-management",
  summaryPage: "/dashboard/asset-management/summary-page",
  assetRequestPage: "/dashboard/asset-request-page",
  assetRequestDetails:"/dashboard/asset-request-page/asset-request-details",
  assetRegisterPage: "/dashboard/asset-register-page",
  addNewAsset: "/dashboard/asset-register-page/add-new-asset",
  viewAssetState: "/dashboard/asset-register-page/view-asset-state",
  depreciationPage: "/dashboard/depreciation-page",
  viewdepreciationState: "/dashboard/depreciation-page/view-depreciation-state",
  addNewDepreciation: "/dashboard/depreciation-page/add-new-depreciation",
  procurementPage: "/dashboard/procurement-page",
  viewProcurementState: "/dashboard/procurement-page/view-procurement-state",
  createProcurementrequest: "/dashboard/procurement-page/create-procurement-request",
  reportPage: "/dashboard/report-page",
  settingPage: "/dashboard/setting-page",


  // FINANCIAL-MANAGEMENT SECTION
  financialDashboard: "/dashboard/financial-management",
  salesManagement: "/dashboard/sales-management",
  view: "/dashboard/sales/view_order",
  customerPage: "/dashboard/sales-management/customer",
  viewCustomer: "/dashboard/sales-management/customer/view",
  viewCustomerOrder: "/dashboard/sales-management/customer/view/order",
  viewOrders: "/dashboard/sales-management/customer/view_order",
  paymentMethod:"/dashboard/sales-management/customer/view/payment-method",
  createReceipt: "/dashboard/sales-management/receipt/create-receipt",
  createMobileReceipt:"/dashboard/sales-management/receipt/create-mobile-receipt",
  confirmReceipt: "/dashboard/sales-management/receipt/confirm-receipt",
  invoiceOverview:"/dashboard/sales-management/sales-invoice",
  createInvoice:"/dashboard/sales-management/sales-invoice/create-invoice",
  previewInvoice :"/dashboard/sales-management/sales-invoice/preview-invoice",
  attachInvoice :"/dashboard/sales-management/sales-invoice/attach-invoice",
  attachReceipent :"/dashboard/sales-management/receipt/attach-receipt", 
  previewReceipt :"/dashboard/sales-management/receipt/preview-receipt", 
  allReceiptView :"/dashboard/sales-management/receipt/all-receipt", 
  shareReceiptView :"/dashboard/sales-management/receipt/share-receipt", 
  viewReceipt :"/dashboard/sales-management/receipt/view-receipt", 
  generateReport :"/dashboard/sales-management/receipt-allocation/generate-report", 
  allocateReceipt :"/dashboard/sales-management/receipt-allocation/allocate-receipt",
 partiallyPaidReceipt :"/dashboard/sales-management/receipt-allocation/partially-paid-receipt",
 advancedPaidReceipt :"/dashboard/sales-management/receipt-allocation/advance-paid-receipt",
 filledPartiallyPaidReceipt :"/dashboard/sales-management/receipt-allocation/filled-partially-paid-receipt",
 filledAvancedPaidReceipt :"/dashboard/sales-management/receipt-allocation/filled-advance-paid-receipt",
 orderReceipt :"/dashboard/sales-management/sales-return/order-receipt", 
 inStoreOverview :"/dashboard/sales-management/sales-return/in-store", 
 financeOverview :"/dashboard/sales-management/sales-return/finance", 
 viewSalesReturns :"/dashboard/sales-management/sales-return/view-returns", 
 issueCreditNote :"/dashboard/sales-management/credit-note/issue-credit-note", 
 creditNote :"/dashboard/sales-management/credit-note/credit-note", 
 creditNote2 :"/dashboard/sales-management/credit-note/credit-notes", 
 viewCreditNote :"/dashboard/sales-management/sales-return/view-credit-note", 
 viewCreditNote2 :"/dashboard/sales-management/sales-return/view-credit-notes", 
 selectVendor :"/dashboard/purchase/select-vendor", 
 unsettledVendor :"/dashboard/purchase/receipt-allocation", 
 unallocatedPayment :"/dashboard/purchase/unallocated-Payment",
 filledUnsettledVendor :"/dashboard/purchase/filled-receipt-allocation",  
 filledUnallocatedPayment :"/dashboard/purchase/filled-unallocated-Payment",
allPurchaseInvoice:"/dashboard/purchase/purchase-invoice/all-purchase-invoice",
nonInventory:"/dashboard/purchase/non-inventory-invoice/non-inventory-invoice",
viewPurchaseInvoice:"/dashboard/purchase/purchase-invoice/view-purchase-invoice",
viewHistory:"/dashboard/purchase/purchase-invoice/view-history",
viewConvertInvoice:"/dashboard/purchase/purchase-invoice/convert-invoice",
viewNoFinancialImplication:"/dashboard/purchase/purchase-invoice/view-existing-purchase-invoice",
viewPurchaseReceipt:"/dashboard/purchase/purchase-invoice/view-purchase-receipt",
allNonInventory:"/dashboard/purchase/non-inventory-invoice/all-non-inventory-invoice",
viewNonInventory:"/dashboard/purchase/non-inventory-invoice/view-non-inventory-invoice",
viewNonInventory2:"/dashboard/purchase/non-inventory-invoice/view-non-inventory-invoices",
allPurchaseReturns:"/dashboard/purchase/purchase-return",
viewPurchaseReturns:"/dashboard/purchase/purchase-return/view-purchase-return",
allDebitNote:"/dashboard/purchase/all-debit-note",
viewDebitNote:"/dashboard/purchase/debit-note/view-debit-note",
previewDebitNote:"/dashboard/purchase/debit-note/preview-debit-note-issued",
sendDebitNote:"/dashboard/purchase/debit-note/send-debit-note-issued",
createRemittance:"/dashboard/purchase/remittance-advice/create-remmittance",
singleInvoice:"/dashboard/purchase/remittance-advice/create-single-invoice",
multipleInvoice:"/dashboard/purchase/remittance-advice/create-multiple-invoice",
attachRemittance:"/dashboard/purchase/remittance-advice/attach-remittance",
previewRemittance:"/dashboard/purchase/remittance-advice/preview-remittance",
editRemittance:"/dashboard/purchase/remittance-advice/edit-remmittance",
allRemittance:"/dashboard/purchase/remittance-advice/all-remmittance",
viewRemittance:"/dashboard/purchase/remittance-advice/view-remmittance",
allocateRemittance:"/dashboard/purchase/remittance-advice/allocate-remmittance",
matchRemittance:"/dashboard/purchase/remittance-advice/match-remmittance",
unallocatedRemittance:"/dashboard/purchase/remittance-advice/unallocated-remmittance",
advancedPaymentRemittance:"/dashboard/purchase/remittance-advice/advanced-payment-remmittance",
filledUnallocatedRemittance:"/dashboard/purchase/remittance-advice/filled-unallocated-remmittance",
filledAdvancedPaymentRemittance:"/dashboard/purchase/remittance-advice/filled-advanced-payment-remmittance",
allPurchaseOrder:"/dashboard/purchase/purchase-order/all-purchase-order",
viewPurchaseOrder:"/dashboard/purchase/purchase-order/view-purchase-order",
previewPurchaseOrder:"/dashboard/purchase/purchase-order/preview-purchase-order",
purchaseOrderHistory:"/dashboard/purchase/purchase-order/purchase-order-history",
vendorHistory:"/dashboard/purchase/purchase-order/vendors",
vendorDetails:"/dashboard/purchase/purchase-order/vendors-details",
addPayment:"/dashboard/purchase/add-payment",
addPayment2:"/dashboard/purchase/add-vendor-payment",
settlePayment:"/dashboard/purchase/settle-vendor-payment",
inventoryWarehouse:"/dashboard/inventory/warehouse",
inventoryWarehouseDetails:"/dashboard/inventory/warehouse-details",
inventoryStores:"/dashboard/inventory/warehouse-store",
singularInventory:"/dashboard/inventory/warehouse-inventory",
inventoryStores2:"/dashboard/inventory/warehouse-stores",
storeView:"/dashboard/inventory/store-view",
initiatePayment:"/dashboard/payment/initiate-payment",
selectProceesor:"/dashboard/payment/initiate-payment/processor",
selectProceesor2:"/dashboard/payment/initiate-payment/processors",
makePayment:"/dashboard/payment/initiate-payment/make-payment",
paymentReceipt:"/dashboard/payment/initiate-payment/payment-receipt",
allPayment:"/dashboard/payment/initiate-payment/all-payment",
viewAllPayment:"/dashboard/payment/initiate-payment/all-payment-view",
accountChart:"/dashboard/account/account-chart",
viewAccountChart:"/dashboard/account/view-account-chart",
createAccountChart:"/dashboard/account/create-account-chart",
importAccountChart:"/dashboard/account/import-account-chart-table",
importChart:"/dashboard/account/import-account-chart",
editAccountChart:"/dashboard/account/edit-account-chart",
allJournal:"/dashboard/account/journal/all-journal",
createJournal:"/dashboard/account/journal/create-journal",
viewJournal:"/dashboard/account/journal/view-journal",
importJournal:"/dashboard/account/journal/import-journal",
reviewJournal:"/dashboard/account/journal/review-journal",
addCard:"/dashboard/banking/add-card",
allTransaction:"/dashboard/banking/all-transactions",
viewCardTransaction:"/dashboard/banking/view-card-transactions",
addBank:"/dashboard/banking/add-bank",
};

